%global crate premouth
%global cargo_install_lib 0

Name:           premouth
Version:        0.1.0
Release:        1.pocketfed%{?dist}
Summary:        Experimental Sargo ABL framebuffer capture and bottom-up dissolve

# Source declares MIT OR Apache-2.0 and every runtime-linked dependency offers
# MIT, so this package selects MIT. LICENSE.dependencies keeps the complete
# generated breakdown; LICENSE.vendor retains every vendored notice, including
# build-only Unicode data that is not linked into the binary.
License:        MIT
URL:            https://github.com/samcday/pocketfed
# Curated, deterministic repack of tools/premouth generated by prepare-srpm.py;
# targets, liveboot/, captured framebuffer/trial/chat artifacts and unrelated
# repository files are excluded.
Source0:        %{name}-%{version}.tar.xz
Source1:        %{name}-%{version}-vendor.tar.xz
Source2:        collect-notices.py
Source3:        test-notify.py
# Upstream supplied this omitted MIT notice after the 2.2.0 crate release;
# the pinned commit and original bytes are documented in the packaging README.
Source4:        drm-fourcc-LICENSE

BuildRequires:  cargo-rpm-macros >= 28
BuildRequires:  cargo
BuildRequires:  rust
BuildRequires:  gcc
BuildRequires:  python3
BuildRequires:  systemd-rpm-macros
# Runtime dependencies for the staged dracut module; ELF library requires are
# generated automatically.
Requires:       dracut
Requires:       systemd
Requires:       plymouth

%description
Premouth is an experimental helper that captures the Android bootloader
framebuffer on Sargo and dissolves it bottom-up into the next boot stage.
This package only makes the opt-in dracut module available: it installs
/usr/libexec/premouth and stages 90premouth under /usr/lib/dracut/modules.d.
Nothing is enabled by default, no initramfs is rebuilt on install, and the
module must be requested explicitly by a device configuration. Boot with
rd.premouth=0 to skip the helper.

%prep
%setup -q -n %{name}-%{version}
%{__tar} -xf %{SOURCE1}
install -Dpm0644 %{SOURCE4} license-supplements/drm-fourcc-2.2.0/LICENSE
%cargo_prep -v vendor

%build
%cargo_build -- --locked
%cargo_license_summary
%{cargo_license} > LICENSE.dependencies
%cargo_vendor_manifest
%{__python3} %{SOURCE2}

%install
install -Dpm0755 target/release/premouth %{buildroot}%{_libexecdir}/premouth
install -Dpm0755 integration/dracut/90premouth/module-setup.sh \
    %{buildroot}%{_prefix}/lib/dracut/modules.d/90premouth/module-setup.sh
install -Dpm0644 integration/dracut/90premouth/premouth.service \
    %{buildroot}%{_prefix}/lib/dracut/modules.d/90premouth/premouth.service
install -Dpm0644 integration/dracut/90premouth/plymouth-start.service.d/10-premouth-yield.conf \
    %{buildroot}%{_prefix}/lib/dracut/modules.d/90premouth/plymouth-start.service.d/10-premouth-yield.conf

%check
%cargo_test -- --locked
%{__python3} %{SOURCE3} target/release/premouth
test -x %{buildroot}%{_libexecdir}/premouth
test -x %{buildroot}%{_prefix}/lib/dracut/modules.d/90premouth/module-setup.sh

%files
%license LICENSE-MIT LICENSE-APACHE Cargo.toml LICENSE.dependencies cargo-vendor.txt LICENSE.vendor
%doc README.md
%{_libexecdir}/premouth
%dir %{_prefix}/lib/dracut/modules.d/90premouth
%{_prefix}/lib/dracut/modules.d/90premouth/module-setup.sh
%{_prefix}/lib/dracut/modules.d/90premouth/premouth.service
%dir %{_prefix}/lib/dracut/modules.d/90premouth/plymouth-start.service.d
%{_prefix}/lib/dracut/modules.d/90premouth/plymouth-start.service.d/10-premouth-yield.conf

%changelog
* Sun Sep 13 2026 Sam Day <me@samcday.com> - 0.1.0-1.pocketfed
- Initial package: opt-in dracut module for the experimental Premouth ABL dissolve
- Install the tested notify helper as /usr/libexec/premouth
- Vendor locked dependencies and retain complete license and notice texts
