ARG BASE_IMAGE=ghcr.io/samcday/pocketfed-base:rawhide
ARG FEDORA_IMAGE=quay.io/fedora/fedora:rawhide
ARG RUST_IMAGE=docker.io/library/rust:1.96-bookworm

FROM ${BASE_IMAGE} AS device-root
COPY devices/google-sargo/samcday-kernel-sdm670-mainline.repo /etc/yum.repos.d/
COPY devices/google-sargo/dracut.conf /etc/dracut.conf.d/60-google-sargo.conf
COPY devices/google-sargo/rpmsg-wwan-blacklist.conf /etc/modprobe.d/
RUN --mount=type=cache,id=pocketfed-google-sargo-arm64-device-dnf,target=/var/cache,sharing=locked \
    set -eux; \
    set -- $(rpm -qa \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra \
        kernel-modules-internal); \
    if [ "$#" -gt 0 ]; then \
        dnf remove -y "$@"; \
    fi; \
    rm -rf /usr/lib/modules/* /lib/modules/*; \
    dnf install -y --setopt=install_weak_deps=False --setopt=keepcache=True kernel; \
    find /boot -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +

FROM device-root AS initrd
RUN set -eu; \
    set -- /usr/lib/modules/*; \
    [ "$#" -eq 1 ]; \
    [ -d "$1" ]; \
    kver="${1##*/}"; \
    install -d /out && \
    dracut \
        --force \
        --hostonly \
        --hostonly-mode=strict \
        --no-hostonly-cmdline \
        --no-hostonly-default-device \
        /out/initramfs.img "$kver" && \
    install -m0644 "/usr/lib/modules/$kver/vmlinuz" /out/vmlinuz && \
    install -m0644 "/usr/lib/modules/$kver/dtb/qcom/sdm670-google-sargo.dtb" /out/sdm670-google-sargo.dtb && \
    printf '%s\n' "$kver" >/out/kver

FROM ${RUST_IMAGE} AS abl-exorcist-build
RUN --mount=type=cache,id=pocketfed-google-sargo-arm64-apt-cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=pocketfed-google-sargo-arm64-apt-lists,target=/var/lib/apt/lists,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    mkdir -p /var/cache/apt/archives/partial /var/lib/apt/lists/partial && \
    apt-get update && \
    apt-get install -y --no-install-recommends llvm
COPY vendor/abl-exorcist /src/abl-exorcist
RUN --mount=type=cache,id=pocketfed-google-sargo-arm64-cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=pocketfed-google-sargo-arm64-cargo-git,target=/usr/local/cargo/git,sharing=locked \
    --mount=type=cache,id=pocketfed-google-sargo-arm64-cargo-target,target=/src/abl-exorcist/target,sharing=locked \
    --mount=type=cache,id=pocketfed-google-sargo-arm64-rustup-downloads,target=/usr/local/rustup/downloads,sharing=locked \
    rustup target add aarch64-unknown-none && \
    install -d /out && \
    cd /src/abl-exorcist && \
    cargo build --locked --release --target aarch64-unknown-none -p abl-exorcist --features cache-sdm670-experiment && \
    llvm-objcopy -O binary target/aarch64-unknown-none/release/abl-exorcist /out/abl-exorcist.bin && \
    cargo build --locked --release -p abl-exorcist-assembler && \
    install -m0755 target/release/abl-exorcist-assembler /out/abl-exorcist-assembler

FROM ${FEDORA_IMAGE} AS bootimg
RUN --mount=type=cache,id=pocketfed-google-sargo-arm64-dnf,target=/var/cache,sharing=locked \
    dnf install -y --setopt=keepcache=True android-tools gzip
COPY --from=initrd /out /in
COPY --from=abl-exorcist-build /out/abl-exorcist.bin /tmp/abl-exorcist.bin
COPY --from=abl-exorcist-build /out/abl-exorcist-assembler /usr/local/bin/abl-exorcist-assembler
RUN install -d /out && \
    gzip -n -9 -c /tmp/abl-exorcist.bin >/tmp/abl-exorcist.bin.gz && \
    abl-exorcist-assembler --ramdisk /in/vmlinuz /in/initramfs.img >/tmp/ablx-ramdisk.img && \
    mkbootimg \
        --header_version 2 \
        --pagesize 4096 \
        --base 0x0 \
        --kernel_offset 0x00008000 \
        --ramdisk_offset 0x04000000 \
        --second_offset 0x00f00000 \
        --tags_offset 0x00000100 \
        --dtb_offset 0x03000000 \
        --dtb /in/sdm670-google-sargo.dtb \
        --kernel /tmp/abl-exorcist.bin.gz \
        --ramdisk /tmp/ablx-ramdisk.img \
        --cmdline '<S> root=LABEL=pfroot rw rootwait rootfstype=ext4 ostree=true init_on_alloc=0 sysrq_always_enabled=1 module_blacklist=rpmsg_wwan_ctrl <E>' \
        -o /out/aboot.img && \
    install -m0644 /in/initramfs.img /out/initramfs.img && \
    install -m0644 /in/kver /out/kver

FROM device-root
COPY --from=bootimg /out /tmp/pocketfed-device
RUN set -eu; \
    kver="$(cat /tmp/pocketfed-device/kver)"; \
    module_dir="/usr/lib/modules/$kver" && \
    [ -d "$module_dir" ] && \
    install -m0644 /tmp/pocketfed-device/initramfs.img "$module_dir/initramfs.img" && \
    install -m0644 /tmp/pocketfed-device/aboot.img "$module_dir/aboot.img" && \
    rm -rf /tmp/pocketfed-device
