#!/bin/sh
set -eu

rpm -q phosh upower upower-libs
systemctl is-enabled upower.service
rpm -q kernel
rpm -q clatd tayga libqmi-utils
rpm -q --qf '%{VERSION}-%{RELEASE}\n' ModemManager |
    grep -Eq '^1\.24\.2-4\.1\.pocketfed\.fc[0-9]+$'

test -x /usr/lib/NetworkManager/dispatcher.d/50-clatd
grep -Fq 'device-add|device-delete)' /usr/lib/NetworkManager/dispatcher.d/50-clatd
grep -Fq 'qmapmux*|rmnet*)' /usr/lib/NetworkManager/dispatcher.d/50-clatd
grep -Fq 'priority mangle + 1; }' /usr/bin/clatd
systemctl is-enabled clatd.service

test -x /usr/libexec/pocketfed-sargo-uim-select
systemctl is-enabled pocketfed-sargo-uim-select.service
test -L /etc/systemd/system/ModemManager.service.wants/pocketfed-sargo-uim-select.service

systemctl is-enabled systemd-boot-check-no-failures.service
systemctl is-enabled qbootctl.service
test -f /usr/lib/ostree-boot/aboot.cfg
grep -Fxq 'POCKETFED_SLOT_SWITCH=qbootctl' /usr/lib/ostree-boot/aboot.cfg
test -x /usr/bin/aboot-deploy
grep -Fq 'finalize_boot_image' /usr/bin/aboot-deploy
grep -Fxq \
    'init_on_alloc=0 sysrq_always_enabled=1 module_blacklist=rpmsg_wwan_ctrl' \
    /usr/lib/ostree-boot/aboot-kargs
test -x /usr/libexec/pocketfed-aboot-finalize
test -x /usr/libexec/abl-exorcist-assembler
rpm -q python3

/usr/libexec/pocketfed-verify-kernel

set -- /usr/lib/modules/*
[ "$#" -eq 1 ]
test -f "$1/vmlinuz"
test -f "$1/dtb/qcom/sdm670-google-sargo.dtb"
test -f "$1/initramfs.img"
test -f "$1/aboot.img"

repacked=$(mktemp)
trap 'rm -f -- "$repacked"' EXIT
options='root=LABEL=pfroot rw rootwait rootfstype=ext4 ostree=/ostree/boot.1/pocketfed/verify/0 ath10k_core.rawmode=1'
/usr/libexec/pocketfed-aboot-finalize \
    --options "$options" \
    --append-options-file /usr/lib/ostree-boot/aboot-kargs \
    "$1/aboot.img" "$repacked"
expected_cmdline="<S> $(cat /usr/lib/ostree-boot/aboot-kargs) $options <E>"
cmdline=$(dd if="$repacked" bs=1 skip=64 count=512 status=none | tr '\000' '\n' | sed -n '1p')
[ "$cmdline" = "$expected_cmdline" ]
