# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate uapi-config

Name:           rust-uapi-config
Version:        0.2.0
Release:        %autorelease
Summary:        Rust implementation of the UAPI Configuration Files Specification

License:        AGPL-3.0-only
URL:            https://crates.io/crates/uapi-config
Source:         %{crates_source}
# * Repository snapshot of the same tag: the published crate omits test-files/,
#   which the unit tests read. Only that directory is extracted, and
#   Cargo.toml's include list keeps it out of the -devel package.
Source10:       https://github.com/Arnavion/uapi-config/archive/v%{version}/uapi-config-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust implementation of the UAPI Configuration Files Specification.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dirs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dirs-devel %{_description}

This package contains library source intended for building other packages which
use the "dirs" feature of the "%{crate}" crate.

%files       -n %{name}+dirs-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
tar -xzf %{SOURCE10} --strip-components=1 uapi-config-%{version}/test-files

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
