# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate embed-doc-image

Name:           rust-embed-doc-image
Version:        0.1.4
Release:        1.1.pocketfed%{?dist}
Summary:        Embed images in Rust documentation

License:        MIT
URL:            https://crates.io/crates/embed-doc-image
Source:         %{crates_source}
# Mark a Markdown example correctly and ignore an example whose images are
# absent from the published crate. Drift Type exercises real image embedding.
Patch0:         embed-doc-image-doctests.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Embed images in Rust documentation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Sep 07 2026 PocketFed maintainers - 0.1.4-1.1.pocketfed
- Package the documentation macro required by Drift Type
