# Downstream source selection and license provenance: see prepare-source.
%bcond check 1
%global crate patricia_dict
%global commit 552c652c75c4d32640e90d702862b93f7e275f2b

Name:           rust-patricia_dict
Version:        0.1.0
Release:        0.3.20260909git552c652%{?dist}
Summary:        Rust reader and writer for Android Patricia dictionaries
SourceLicense:  GPL-3.0-only
License:        GPL-3.0-only AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)
URL:            https://gitlab.com/InsanePrawn/android-patricia-dict
# Generated by prepare-source from the pinned licensed public source commit.
# Includes author-confirmed downstream license metadata; excludes dictionary data.
Source0:        pocketfed-patricia-rust-gpl3-%{commit}.tar.gz
Source1:        patricia_dict_cli.1
BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Patricia Dict provides access to Android keyboard dictionary formats, with
prefix search, stored word probabilities, context scores and shortcuts. Formats
2 and 402 are read-only; format 403 supports explicit dictionary updates.}

%description %{_description}

%package devel
License:        GPL-3.0-only
Summary:        %{summary}
BuildArch:      noarch

%description devel %{_description}

This package contains Rust library source for the patricia_dict crate.

%files devel
%license %{crate_instdir}/COPYING
%license %{crate_instdir}/LICENSE.dependencies
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/LICENSE-PROVENANCE.md
%dir %{crate_instdir}
%{crate_instdir}/.cargo-checksum.json
%{crate_instdir}/Cargo.toml
%{crate_instdir}/src/

%package -n %{name}+default-devel
License:        GPL-3.0-only
Summary:        Default feature of the patricia_dict crate
BuildArch:      noarch

%description -n %{name}+default-devel
This package contains metadata for the default feature of patricia_dict.

%files -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package -n patricia-dict-tools
Summary:        Command-line access to Android Patricia dictionaries
# From cargo2rpm license-summary for the statically linked runtime crates.
License:        GPL-3.0-only AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)

%description -n patricia-dict-tools %{_description}

This package contains a command-line dictionary utility.
Dictionary data is available in separate language packages.

%files -n patricia-dict-tools
%license COPYING LICENSE.dependencies
%doc README.md LICENSE-PROVENANCE.md
%{_bindir}/patricia_dict_cli
%{_mandir}/man1/patricia_dict_cli.1*

%prep
%autosetup -n %{crate}
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%cargo_license_summary
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm 0644 %{SOURCE1} %{buildroot}%{_mandir}/man1/patricia_dict_cli.1

%if %{with check}
%check
# The curated package has unit/doc tests; corpus tests live in upstream source.
%cargo_test
%endif

%changelog
* Wed Sep 09 2026 Sam Day <me@samcday.com> - 0.1.0-0.3.20260909git552c652
- Correct the historical release number in the prior changelog entry

* Wed Sep 09 2026 Sam Day <me@samcday.com> - 0.1.0-0.2.20260909git552c652
- Advance to the Patricia revision used by the tested swipe integration
- Preserve author-confirmed GPL-3.0-only metadata; no downstream Rust changes

* Mon Sep 07 2026 Sam Day <me@samcday.com> - 0.1.0-0.1.20260907gitcdab42d
- Package pinned reader with author-confirmed GPL-3.0-only license metadata
- Keep dictionary data separate from the Rust library and command-line tools
