# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate tokio-udev

Name:           rust-tokio-udev
Version:        0.10.0
Release:        %autorelease
Summary:        Non-blocking/Asynchronous Tokio support for udev device events

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/tokio-udev
Source:         %{crates_source}
# * The published crate omits the license texts that the upstream repository
#   ships in its REUSE LICENSES/ directory; take them from the matching tag.
Source10:       https://raw.githubusercontent.com/jeandudey/tokio-udev/v%{version}/LICENSES/Apache-2.0.txt
Source11:       https://raw.githubusercontent.com/jeandudey/tokio-udev/v%{version}/LICENSES/MIT.txt

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Non-blocking/Asynchronous Tokio support for udev device events.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSES/Apache-2.0.txt
%license %{crate_instdir}/LICENSES/MIT.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hwdb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hwdb-devel %{_description}

This package contains library source intended for building other packages which
use the "hwdb" feature of the "%{crate}" crate.

%files       -n %{name}+hwdb-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
mkdir -p LICENSES
cp -pav %{SOURCE10} %{SOURCE11} LICENSES/
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
