[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=rawhide
Architecture=arm64

[Output]
Format=directory
Output=rootfs
ImageId=pocketfed-base
OutputDirectory=mkosi.output
ManifestFormat=json
CompressOutput=no
SplitArtifacts=

[Content]
Bootable=no
Bootloader=none
UnifiedKernelImages=none
KernelModulesInitrd=no
MakeInitrd=no
Ssh=never
WithRecommends=no
WithDocs=no
CleanPackageMetadata=no
ExtraTrees=mkosi.local/kernel
RemoveFiles=
    /etc/fstab
    /etc/locale.conf
    /etc/vconsole.conf
SELinuxRelabel=yes

Packages=
    android-tools
    atheros-firmware
    bash
    blob-wrangler
    bootc
    container-selinux
    coreutils
    cryptsetup
    curl
    dnf5
    dnf5-plugins
    dosfstools
    dracut
    e2fsprogs
    glibc-langpack-en
    hostname
    iio-sensor-proxy
    iproute
    iputils
    kmod
    less
    linux-firmware
    lvm2
    ModemManager
    NetworkManager
    NetworkManager-wifi
    NetworkManager-wwan
    nss-altfiles
    openssh-clients
    openssh-server
    ostree
    passwd
    policycoreutils
    polkit
    procps-ng
    qbootctl
    rpm-ostree
    rmtfs
    selinux-policy-targeted
    shadow-utils
    skopeo
    sudo
    systemd
    systemd-pam
    systemd-resolved
    systemd-udev
    tqftpserv
    tzdata
    util-linux
    vim-minimal
    xfsprogs
    zram-generator-defaults

[Build]
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
SandboxTrees=mkosi.sandbox
ToolsTree=yes
ToolsTreeDistribution=fedora
ToolsTreeRelease=rawhide
ToolsTreePackages=
    android-tools
    bootc
    rpm-ostree
    skopeo
