[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=rawhide
Architecture=arm64

[Output]
Format=directory
ImageId=pocketfed-base
OutputDirectory=mkosi.output
ManifestFormat=json

[Content]
Bootable=no
Bootloader=none
UnifiedKernelImages=none
KernelModulesInitrd=no
MakeInitrd=no
Ssh=never
WithRecommends=no
WithDocs=no
CleanPackageMetadata=no
RemoveFiles=
    /etc/fstab
    /etc/locale.conf
    /etc/vconsole.conf
SELinuxRelabel=yes
SourceDateEpoch=0

Packages=
    alsa-ucm
    alsa-utils
    atheros-firmware
    bash
    blob-wrangler
    bootc
    container-selinux
    coreutils
    cryptsetup
    curl
    default-editor
    device-mapper-libs
    dnf5
    dnf5-plugins
    dosfstools
    dracut
    e2fsprogs
    glibc-langpack-en
    gstreamer1-plugin-openh264
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-good
    gstreamer1-plugins-ugly-free
    hostname
    iio-sensor-proxy
    iproute
    iputils
    kernel
    kmod
    less
    libblkid
    libmd
    linux-firmware
    lvm2
    mesa-dri-drivers
    ModemManager
    NetworkManager
    NetworkManager-bluetooth
    NetworkManager-config-connectivity-fedora
    NetworkManager-wifi
    NetworkManager-wwan
    nss-altfiles
    openssh-clients
    openssh-server
    ostree
    passwd
    pavucontrol
    pipewire-alsa
    pipewire-gstreamer
    pipewire-pulseaudio
    pipewire-utils
    plymouth
    plymouth-system-theme
    policycoreutils
    polkit
    procps-ng
    qbootctl
    qcom-firmware
    rpm-ostree
    rmtfs
    selinux-policy-targeted
    shadow-utils
    sudo
    systemd
    systemd-pam
    systemd-resolved
    systemd-udev
    toolbox
    tqftpserv
    tzdata
    util-linux
    vim-minimal
    wireplumber
    xfsprogs
    zram-generator-defaults

BuildPackages=
    glibc-devel
    libatomic
    libblkid-devel
    libmd-devel
    lvm2-devel

[Build]
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
BuildSources=
    ../vendor/make-dynpart-mappings:make-dynpart-mappings
Incremental=yes
SandboxTrees=mkosi.sandbox
ToolsTree=yes
ToolsTreeDistribution=fedora
ToolsTreeRelease=rawhide
ToolsTreePackages=
    bootc
    gcc
    make
    pkgconf-pkg-config
    rpm-ostree
    umoci
