[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=rawhide
Architecture=arm64

[Output]
Format=directory
Output=rootfs
ImageId=pocketfed-base
OutputDirectory=mkosi.output
ManifestFormat=json
CompressOutput=no
SplitArtifacts=

[Content]
Bootable=no
Bootloader=none
UnifiedKernelImages=none
KernelModulesInitrd=no
MakeInitrd=no
Ssh=never
WithRecommends=no
WithDocs=no
CleanPackageMetadata=no
RemoveFiles=
    /etc/fstab

Packages=
    bash
    bootc
    container-selinux
    coreutils
    cryptsetup
    curl
    dnf5
    dnf5-plugins
    dosfstools
    e2fsprogs
    hostname
    iproute
    iputils
    kmod
    less
    lvm2
    NetworkManager
    nss-altfiles
    openssh-clients
    openssh-server
    ostree
    passwd
    policycoreutils
    polkit
    procps-ng
    rpm-ostree
    selinux-policy-targeted
    shadow-utils
    skopeo
    sudo
    systemd
    systemd-pam
    systemd-resolved
    systemd-udev
    util-linux
    vim-minimal
    xfsprogs
    zram-generator-defaults

RemovePackages=
    bootupd
    dracut-config-rescue
    kernel
    kernel-core
    kernel-debug-core
    kernel-modules
    kernel-modules-core
    kernel-modules-extra
    linux-firmware

[Build]
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
