%global datacommit 55e6d1c64ad72481d5615113b1c94f0716617016
%global toolcommit a009d2c98da9749bf6ae4d92ef5fb3d3e945530f

Name:           android-patricia-dictionaries
Version:        54
Release:        0.1.20260907git55e6d1c%{?dist}
Summary:        Word frequency data for Android Patricia dictionary readers
SourceLicense:  GPL-3.0-only AND Apache-2.0
License:        GPL-3.0-only
URL:            https://codeberg.org/Helium314/aosp-dictionaries
# Source archives are generated by prepare-sources from immutable, hashed inputs.
Source0:        %{name}-%{datacommit}.tar.gz
# Selected build-only AOSP Java sources (Apache-2.0), with full notices.
Source1:        aosp-dicttool-%{toolcommit}.tar.gz
Source2:        PROVENANCE.md
Source3:        build-dictionary
Patch0:         dicttool-v202-offensive.patch
BuildArch:      noarch
BuildRequires:  java-latest-openjdk-devel
BuildRequires:  python3

%description
Dictionary word frequencies, word pairs and shortcuts for consumers of Android
Patricia dictionaries. Individual language data is packaged separately.

%package en-US
Summary:        US English Android Patricia dictionary

%description en-US
US English words, stored probabilities, word pairs and shortcuts from the pinned
AOSP-compatible dictionary collection. The dictionary is rebuilt from its
editable source and verified byte-for-byte against the upstream artifact.

%prep
%setup -q -n %{name}-%{version} -a 1
%patch -P 0 -p1 -d dicttool
cp -p %{SOURCE2} PROVENANCE.md

%build
%{python3} %{SOURCE3} dicttool main_en_US.combined en_US.dict

%install
install -Dpm 0644 en_US.dict %{buildroot}%{_datadir}/android-patricia-dictionaries/en_US.dict

%check
printf 'bd950ef4b57655120eee65cee62a5d216a63f721d9a8bb759ce2022437840443  en_US.dict\n' | sha256sum -c -
printf '73308519ff089c73baa35e08f25087bb62ed4a6bf2f96af3efb402187f7c9edb  main_en_US.combined\n' | sha256sum -c -

%files en-US
%license COPYING
%doc PROVENANCE.md main_en_US.source
%dir %{_datadir}/android-patricia-dictionaries
%{_datadir}/android-patricia-dictionaries/en_US.dict

%changelog
* Mon Sep 07 2026 Sam Day <me@samcday.com> - 54-0.1.20260907git55e6d1c
- Package independently reusable US English Patricia data with source provenance
- Rebuild the exact upstream v202 dictionary using source-built AOSP tooling
