ARG BASE_IMAGE=ghcr.io/samcday/pocketfed-base:rawhide

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="PocketFed Phosh"
LABEL org.opencontainers.image.description="PocketFed Phosh desktop layer"

RUN --mount=type=cache,id=pocketfed-phosh-arm64-dnf,target=/var/cache,sharing=locked \
    set -eux; \
    dnf install -y --setopt=install_weak_deps=False --setopt=keepcache=True \
        calls \
        chatty \
        default-fonts-core-emoji \
        epiphany \
        feedbackd \
        glib-networking \
        gnome-calculator \
        gnome-calendar \
        gnome-clocks \
        gnome-console \
        gnome-contacts \
        gnome-control-center \
        gnome-keyring \
        gnome-keyring-pam \
        gnome-maps \
        gnome-photos \
        gnome-software \
        nautilus \
        phoc \
        phosh \
        phosh-mobile-settings \
        phosh-tour \
        phrog \
        pinentry-gnome3 \
        showtime \
        stevia \
        upower \
        xdg-desktop-portal \
        xdg-desktop-portal-gtk \
        xdg-user-dirs-gtk

RUN set -eux; \
    systemctl enable phrog.service; \
    bootc container lint --no-truncate
