ARG BASE_IMAGE=ghcr.io/samcday/pocketfed-base:rawhide

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="PocketFed Phosh"
LABEL org.opencontainers.image.description="PocketFed Phosh desktop layer"

RUN set -eux; \
    dnf install -y --setopt=install_weak_deps=False \
        calls \
        chatty \
        epiphany \
        feedbackd \
        glib-networking \
        gnome-calculator \
        gnome-calendar \
        gnome-clocks \
        gnome-console \
        gnome-contacts \
        gnome-maps \
        gnome-photos \
        gnome-software \
        phoc \
        phosh \
        phosh-mobile-settings \
        phosh-tour \
        phrog \
        pinentry-gnome3 \
        showtime \
        stevia \
        xdg-desktop-portal \
        xdg-desktop-portal-gtk \
        xdg-user-dirs-gtk; \
    dnf clean all

RUN set -eux; \
    systemctl enable phrog.service; \
    bootc container lint --no-truncate
